version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /hackathon/featurecounts.wdl
    testParameterFiles:
        - /hackathon/featurecounts_inputs_terra.json
    name: feature_counts_wdl
