version: 1.2
workflows:
  name: feature_counts_wkf
  - subclass: WDL
     primaryDescriptorPath: /hackathon/featurecounts.wdl
     testParameterFiles:
        - /hackathon/featurecounts_inputs_terra.json
