#!/bin/bash

cd /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution
tmpDir=$(mkdir -p "/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/tmp.8ac1c813" && echo "/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/tmp.8ac1c813")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution

)
out99f417db="${tmpDir}/out.$$" err99f417db="${tmpDir}/err.$$"
mkfifo "$out99f417db" "$err99f417db"
trap 'rm "$out99f417db" "$err99f417db"' EXIT
touch '/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/stdout' '/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/stderr'
tee '/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/stdout' < "$out99f417db" &
tee '/home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/stderr' < "$err99f417db" >&2 &
(
cd /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution


echo HelloString > hello.txt
)  > "$out99f417db" 2> "$err99f417db"
echo $? > /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution
sync


)
mv /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/rc.tmp /home/user05/myworkflows_wdl/cromwell-executions/hellowdl/99f417db-472f-4c6c-8072-8d83ce999000/call-helloworld/execution/rc
